### ISSUE TITLE
Include player in rewind function for NQ clients on FTE servers

### ISSUE THREAD

**Issue by shlevon** [ceeeKay/QCAntilag#8]

**Comment by ceeeKay** [comment]
is this still an issue/can you provide some more detail here?

**Comment by shlevon** [comment]
Better question for Reki - he actually said maybe don't do this part for
netquake clients as it might interfere with rocket jumping last time it
came up.  So tbh you can probably just close it.

**Comment by ceeeKay** [comment]
closing until/unless we figure this should be added
